### ISSUE TITLE
TLS part 2: Enable TLS for Prometheus alerting and self-monitoring

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/alertmanager-k8s-operator#165]
Tracking issue: canonical/cos-lite-bundle#75 

canonical/alertmanager-k8s-operator#164 enabled TLS for Alertmanager but both scrape target and `cluster_info` are still HTTP.

Potentially blocked by https://github.com/canonical/tls-certificates-interface/issues/46 (prom may not be able to scrape).

Related: https://github.com/canonical/charm-microk8s/pull/88

TODO:
- [ ] Update the self-scrape config to use https scheme
- [ ] Update the `cluster_info` logic in the `alerting` lib so prometheus charm generates the `alertmanagers` section correctly.
- [ ] Think what needs to be changed so that prometheus WITHOUT tls is able to scrape alertmanager WITH tls enabled (probably need to set insecure-skip-verify somewhere in prometheus).

**Comment by sed-i** [comment]
In `def self_scraping_job(self)`, `external_url.hostname` is provided by `Traefik`, for instance:

![imagen](https://github.com/canonical/alertmanager-k8s-operator/assets/939888/7479c8e6-ab8a-495b-a2ca-ba470fe11fec)


On the other hand `self.server_cert.cert` is provided by `CertManager`.

If `Traefik` doesn't support `HTTPS` in the `URLs` it provides, we can end up generating an invalid URL

_Originally posted by @Abuelodelanada in https://github.com/canonical/alertmanager-k8s-operator/pull/164#discussion_r1238932652_
