### ISSUE TITLE
Support proxies

### ISSUE THREAD

**Issue by dstathis** [canonical/alertmanager-k8s-operator#178]
Looks like this should just be setting the http_proxy environment variable for Grafana based on a config value. We should likely do this for Alertmanager as well

_Originally posted by @dstathis in https://github.com/canonical/grafana-k8s-operator/issues/240#issuecomment-1668025553_

**Comment by dstathis** [comment]
See the similar issue for Grafana for more info. This will likely just be setting environment variables.

**Comment by lucabello** [comment]
The Grafana issue is https://github.com/canonical/grafana-k8s-operator/issues/240; opening a PR here with the same approach :)

**Comment by lucabello** [comment]
Done in https://github.com/canonical/alertmanager-k8s-operator/pull/195
