### ISSUE TITLE
Race in alertmanager configuration

### ISSUE THREAD

**Issue by simskij** [canonical/alertmanager-k8s-operator#189]
### Bug Description

There seems to be a race in the `alertmanager_dispatch` library that sometimes prevents Prometheus from sending alerts to alertmanager.

### To Reproduce

1. `juju deploy cos-lite --channel edge --trust`
2. check the alertmanager ui
3. remove the prometheus alerting relation and add it back
4. check ui again

### Environment

n/a

### Relevant log output

```shell
n/a
```

**Comment by Abuelodelanada** [comment]
@simskij @PietroPasotti I'm no able to reproduce this bug.


Look:

1. Deploy cos-lite: `juju deploy cos-lite --trust --channel=edge`
```shell
$ juju status
Model  Controller  Cloud/Region        Version  SLA          Timestamp
cos    microk8s    microk8s/localhost  3.1.6    unsupported  10:15:29-03:00

App           Version  Status  Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.25.0   active      1  alertmanager-k8s  edge      96  10.152.183.17   no       
catalogue              active      1  catalogue-k8s     edge      31  10.152.183.123  no       
grafana       9.2.1    active      1  grafana-k8s       edge      93  10.152.183.169  no       
loki          2.7.4    active      1  loki-k8s          edge     105  10.152.183.205  no       
prometheus    2.47.2   active      1  prometheus-k8s    edge     157  10.152.183.133  no       
traefik       2.10.4   active      1  traefik-k8s       edge     164  192.168.1.250   no       

Unit             Workload  Agent  Address      Ports  Message
alertmanager/0*  active    idle   10.1.38.83          
catalogue/0*     active    idle   10.1.38.109         
grafana/0*       active    idle   10.1.38.126         
loki/0*          active    idle   10.1.38.78          
prometheus/0*    active    idle   10.1.38.77          
traefik/0*       active    idle   10.1.38.91  
```

2. Check Alertmanager UI:
![image](https://github.com/canonical/alertmanager-k8s-operator/assets/939888/908ec957-92f2-472c-b6f0-9347f366778e)

3. Remove prometheus alerting relation: `juju remove-relation prometheus alertmanager:alerting`
4. Check Alertmanager UI **(after ~30 seconds)**:
![image](https://github.com/canonical/alertmanager-k8s-operator/assets/939888/c0b9fe6e-2ec9-4d79-8fcb-d8c09bd5c77a)
5. Add prometheus alerting relation back: `juju relate prometheus alertmanager:alerting`
6. Check Alertmanager UI again **(after ~30 seconds)**:
![image](https://github.com/canonical/alertmanager-k8s-operator/assets/939888/5784308a-2d1d-4ae5-8e9f-28876c558925)

**Comment by Abuelodelanada** [comment]
I close it for now.
Let's open it again if the issue re-appears
