### ISSUE TITLE
configurable API port

### ISSUE THREAD

**Issue by sed-i** [canonical/alertmanager-k8s-operator#19]
Alertmanager has currently two port numbers hard-coded as a "static" class attributes: API port, 9093 and HA port, 9094.
It would be helpful for ingress to have the API port more visible/obvious.

https://github.com/canonical/alertmanager-operator/pull/17#discussion_r671532981

**Comment by mmanciop** [comment]
We should expose those ports meaningfully over the relations, but there is no use-case at the moment to make them configurable as in `juju config`.
