### ISSUE TITLE
Add an action to test external integrations like Pagerduty

### ISSUE THREAD

**Issue by marcusboden** [canonical/alertmanager-k8s-operator#203]
### Enhancement Proposal

It would be helpful to trigger test alerts as an action.
Ideally it could have options for the alert body (i.e. labels) and maybe limit it to some a single receiver. This would allow us to test the alerting of a cloud without creating an actual alert (e.g. by stopping grafana).

**Comment by sed-i** [comment]
Would it work for you to relate avalanche to prometheus, for testing purposes?
Related issue: https://github.com/canonical/avalanche-k8s-operator/issues/41

**Comment by marcusboden** [comment]
Maybe, once the mentioned issue is solved. But that would mean the we need to deploy an extra charm on customer clouds, just for quick testing. It's possible, but I would prefer a (configurable) action.

**Comment by sed-i** [comment]
Then how about [`amtool alert add`](https://manpages.debian.org/testing/prometheus-alertmanager/amtool.1.en.html)? It's already in the [workload container](https://github.com/canonical/alertmanager-rock/blob/c0e06b43e246a3a35fd62619bdeead6433bd79a8/0.25.0/rockcraft.yaml#L52).

**Comment by marcusboden** [comment]
Yeah, that works quite well for testing, thanks. Still would be nice to define a simple action for that, if you find the time.

**Comment by sed-i** [comment]
Added to the idea bank. Closing for now.
Feel free to reopen is `juju ssh` isn't ergonomic enough.
