### ISSUE TITLE
Wrong Alert's source URL

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/alertmanager-k8s-operator#206]
### Bug Description

Despite of the fact Alertmanager and Prometheus are behind an ingress, the source of the alert use k8s-based URL

![image](https://github.com/canonical/alertmanager-k8s-operator/assets/939888/f7549e56-6c81-4ed5-9de4-1beeaf5026ec)

### To Reproduce

1. Deploy cos-lite bundle
2. In Alertmanager UI check for the Source of the alert.

### Environment

- juju 3.1.6
- cos-lite bundle

### Relevant log output

```shell
-
```

**Comment by mcarvalhor** [comment]
Affects us too.

**Comment by cbartz** [comment]
This affects us too, and also the [ExternalURL](https://prometheus.io/docs/alerting/latest/notifications/) (used in backlinks for the alert title in slack notifications) is set to the k8s-based URL. I wonder if changing `https://github.com/canonical/alertmanager-k8s-operator/blob/main/src/charm.py#L168` to use `_external_url` could at least fix the ExternalURL issue.

**Comment by marcusboden** [comment]
We're also affected by this. Having to fix the URLs each time is time consuming in emergencies.

**Comment by lucabello** [comment]
Increasing the priority on this one :)
