### ISSUE TITLE
Set external URL as a Grafana Data Source

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/alertmanager-k8s-operator#224]
### Enhancement Proposal

Unlike Loki, if the relation between Alertmanager and Traefik is established, Alertmanager set fqdn address instead of the external one as a Grafana Data Source.

![image](https://github.com/canonical/alertmanager-k8s-operator/assets/939888/656077ca-9d9e-4182-a644-051c21b944c3)

**Comment by IbraAoad** [comment]
Adding to the above that when trying out the following scenario (Deploy COS with TLS then remove all TLS relations), Alertmanager data source is still stuck on https

![image](https://github.com/canonical/alertmanager-k8s-operator/assets/63512482/eeb0c758-5a85-423b-97b7-e70079375c57)

I tried this with below revs

```
App           Version  Status  Scale  Charm                     Channel      Rev  Address         Exposed  Message
alertmanager  0.27.0   active      1  alertmanager-k8s          latest/edge  114  10.152.183.85   no       
ca                     active      1  self-signed-certificates  latest/edge  141  10.152.183.170  no       
catalogue              active      1  catalogue-k8s             latest/edge   39  10.152.183.134  no       
grafana       9.5.3    active      1  grafana-k8s               latest/edge  113  10.152.183.94   no          
traefik       v2.11.0  active      1  traefik-k8s               latest/edge  191  192.168.100.69  no 
```
