### ISSUE TITLE
Fix CodeQL scheduling

### ISSUE THREAD

**Issue by sed-i** [canonical/alertmanager-k8s-operator#42]
> I wonder if we should run it also nightly on main.

_Originally posted by @mmanciop in https://github.com/canonical/alertmanager-operator/pull/39#discussion_r722875617_

> I think it might make sense to run this check on any PR, irrespective of the target branch (these are github workflows we do not current use, but still)

_Originally posted by @mmanciop in https://github.com/canonical/alertmanager-operator/pull/39#discussion_r722874856_

**Comment by SamirPS** [comment]
Hello you want the codeql-analysis workflow run nightly thanks to cron
